image : microsoft/dotnet:latest

services:
    - mariadb

variables:
  tests: "Tests"
  integration_tests: "IntegrationTests"
  MYSQL_DATABASE: mydb
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"


stages:
  - build
  - verify
  - unit-test
  - integration-test
  - package

before_script:
    - "dotnet --info"
    - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
    - "apt-get install -y nodejs"
    - "npm install -g @angular/cli"
    - apt-get update && apt-get --assume-yes install mariadb-client
    - mysql --user=root --password="" --host=mariadb < "ScriptDB.sql"
    - ping mariadb -c 4

    
build:
  stage: build
  script:
    - dotnet build /p:RunCodeAnalysis=false IntranetAziendale/IntranetAziendale.sln

verify:
  stage: verify
  script:
    - dotnet build --no-incremental /p:RunCodeAnalysis=true IntranetAziendale/IntranetAziendale.sln
    
unit-test:
  stage: unit-test
  script:
   - dotnet test IntranetAziendale/UnitTests/UnitTests.csproj
   
integration-test:
  stage: integration-test
  script:
   - dotnet test IntranetAziendale/IntegrationTests/IntegrationTests.csproj   

package:
  stage: package 
  script:
    - dotnet pack IntranetAziendale/IntranetAziendale.sln -o Package