image : microsoft/dotnet:latest

variables:
    tests: "Tests"
    integration_tests: "IntegrationTests"

stages:
    - build
    - verify
    - unit-test
    - integration-test
    - package
    - release
    - deploy

build:
    stage: build
    script:
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g @angular/cli
        - dotnet build /p:RunCodeAnalysis=false IntranetAziendale/IntranetAziendale.sln

verify:
    stage: verify
    script:
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g @angular/cli
        - dotnet build --no-incremental /p:RunCodeAnalysis=true IntranetAziendale/IntranetAziendale.sln
    
unit-test:
    stage: unit-test
    script:
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g @angular/cli
        - dotnet test IntranetAziendale/UnitTests/UnitTests.csproj
   
integration-test:
    stage: integration-test
    variables:
        MYSQL_DATABASE: mydb
        MYSQL_ALLOW_EMPTY_PASSWORD: "1"
        CI_VERSION: "1.0.${CI_BUILD_ID}"
    services:
    - mariadb

    script:
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g @angular/cli
        - apt-get update && apt-get --assume-yes install mariadb-client
        - mysql --user=root --password="" --host=mariadb < "ScriptDB.sql"
        - dotnet test IntranetAziendale/IntegrationTests/IntegrationTests.csproj   

package:
    stage: package 
    script:
        - curl -sL https://deb.nodesource.com/setup_10.x | bash -
        - apt-get install -y nodejs
        - npm install -g @angular/cli
        - dotnet pack IntranetAziendale/IntranetAziendale.sln -o Package
    
release:
    stage: release
    script:
        - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:B8vyi17Jrab3R_bAtzwd" --data '{"name":"Assignment 1 - Release '$CI_VERSION'", "tag_name":"'$CI_VERSION'", "ref":"'"$CI_COMMIT_SHA"'", "description":"Release '$CI_VERSION'"}' --request POST https://gitlab.com/api/v4/projects/14884438/releases
    only:
        - master
        
deploy:
    stage: deploy
    
    image: docker:latest
    services:
        - docker:dind
    script: 
        - docker login --username=f.beltramelli@campus.unimib.it --password=$HEROKU_API registry.heroku.com
        - docker build -t deployintranetaziendale -f Dockerfile .
        - docker tag deployintranetaziendale registry.heroku.com/deployintranetaziendale/web
        - docker push registry.heroku.com/deployintranetaziendale/web
    only:
        - master