image : microsoft/dotnet:latest

stages:
  - build

before_script:
    - "dotnet --info"
    - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
    - "apt-get install -y nodejs"
    - "npm install -g @angular/cli"
    
build:
  stage: build
  script:
    - dotnet build

